package bundlegen

import (
	"errors"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

// seedSingleLayerBundle writes a one-layer bundle into t.TempDir() by running
// Add against a small inline OpenAPI doc. The shared test helper across this
// package's existing tests uses the same in-process Add path, so the produced
// descriptors.binpb matches what the runtime would see at boot.
func seedSingleLayerBundle(t *testing.T) (bundleDir, version string) {
	t.Helper()
	const doc = `{"openapi":"3.0.0","info":{"title":"t","version":"2026-05-17"},
"paths":{"/v3/echo":{"post":{
"requestBody":{"content":{"application/json":{"schema":{"$ref":"#/components/schemas/Req"}}}},
"responses":{"200":{"content":{"application/json":{"schema":{"$ref":"#/components/schemas/Req"}}}}}}}},
"components":{"schemas":{"Req":{"type":"object","properties":{"text":{"type":"string"}}}}}}`
	bundleDir = t.TempDir()
	src := filepath.Join(t.TempDir(), "openapi.json")
	if err := os.WriteFile(src, []byte(doc), 0o600); err != nil {
		t.Fatalf("write openapi: %v", err)
	}
	if err := Add(src, bundleDir); err != nil {
		t.Fatalf("seed bundle: %v", err)
	}
	return bundleDir, "2026-05-17"
}

// requireProtocGenES skips the test cleanly when protoc-gen-es is not on
// PATH. CI without Node tooling installed must still go green; the error
// path is exercised by TestGenTSClientReportsMissingProtocGenES which uses
// t.Setenv("PATH", "") and runs unconditionally.
func requireProtocGenES(t *testing.T) {
	t.Helper()
	if _, err := exec.LookPath("protoc-gen-es"); err != nil {
		t.Skipf("skipping: protoc-gen-es not on PATH (%v); install: npm install -g @bufbuild/protoc-gen-es", err)
	}
}

func TestGenTSClientEmitsMessageClasses(t *testing.T) {
	requireProtocGenES(t)
	bundleDir, _ := seedSingleLayerBundle(t)
	outDir := filepath.Join(t.TempDir(), "client")
	res, err := GenTSClient(bundleDir, outDir, "")
	if err != nil {
		t.Fatalf("GenTSClient: %v", err)
	}
	if len(res.MessageFiles) == 0 {
		t.Fatalf("GenTSClient: expected at least one emitted message file, got none")
	}
	// MessageFiles must be sorted ascending so the status line and downstream
	// chunks see a deterministic ordering across runs.
	prev := ""
	for _, rel := range res.MessageFiles {
		if prev != "" && rel < prev {
			t.Errorf("MessageFiles not sorted ascending: %q < %q", rel, prev)
		}
		prev = rel
		if !strings.HasSuffix(rel, ".ts") {
			t.Errorf("emitted file %q does not end in .ts", rel)
		}
		// Path must be relative — never absolute, never climb out of --out.
		if filepath.IsAbs(rel) {
			t.Errorf("emitted file %q must be relative to --out", rel)
		}
		abs := filepath.Join(outDir, rel)
		info, statErr := os.Stat(abs)
		if statErr != nil {
			t.Errorf("emitted file %q missing on disk: %v", rel, statErr)
			continue
		}
		if info.Size() == 0 {
			t.Errorf("emitted file %q is empty", rel)
		}
		// Sanity-check the protoc-gen-es header line so a future upstream
		// change that flips parameter handling doesn't silently regress us.
		body, readErr := os.ReadFile(abs)
		if readErr != nil {
			t.Errorf("read emitted file %q: %v", rel, readErr)
			continue
		}
		if !strings.Contains(string(body), "@generated by protoc-gen-es") {
			t.Errorf("emitted file %q missing protoc-gen-es header line", rel)
		}
	}
}

func TestGenTSClientReportsMissingProtocGenES(t *testing.T) {
	// Force LookPath("protoc-gen-es") to fail by emptying PATH for this test.
	// This is the structured-error contract: the CLI layer relies on the
	// returned error to surface the install hint.
	t.Setenv("PATH", "")
	bundleDir, _ := seedSingleLayerBundle(t)
	outDir := filepath.Join(t.TempDir(), "client")
	_, err := GenTSClient(bundleDir, outDir, "")
	if err == nil {
		t.Fatal("GenTSClient with empty PATH: want an error, got nil")
	}
	var missing *ProtocGenESMissingError
	if !errors.As(err, &missing) {
		t.Fatalf("error type: got %T (%v), want *ProtocGenESMissingError", err, err)
	}
	msg := err.Error()
	for _, want := range []string{"protoc-gen-es", "not found", "npm install"} {
		if !strings.Contains(msg, want) {
			t.Errorf("error message missing %q substring:\n%s", want, msg)
		}
	}
}
