package bundlegen

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// --- unit tests: operation-ID derivation ---
//
// These tests exercise the pure derivation helpers used by emitRoutesFile so
// the contract is pinned independently of whether protoc-gen-es is on PATH —
// the integration test below is the one that does require the plugin.

func TestDeriveOperationIDFromMethodPath(t *testing.T) {
	cases := []struct {
		method, path, want string
	}{
		{"POST", "/v3/echo", "postV3Echo"},
		{"GET", "/v3/items", "getV3Items"},
		// Path params are skipped: a literal "{id}" segment contributes no
		// camel-case word so the derived ID stays stable across whatever the
		// parameter happens to be called this week.
		{"GET", "/v3/items/{id}", "getV3Items"},
		{"PUT", "/v3/items/{id}/comments", "putV3ItemsComments"},
		// Dashes and dots in segments become word boundaries.
		{"DELETE", "/v3/foo-bar.baz", "deleteV3FooBarBaz"},
		// Root path → bare method name (stable lower-case).
		{"GET", "/", "get"},
		// Empty path (defensive) → bare method name.
		{"GET", "", "get"},
		// Method is normalised to lower-case regardless of input casing.
		{"post", "/items", "postItems"},
	}
	for _, tc := range cases {
		got := deriveOperationID(tc.method, tc.path)
		if got != tc.want {
			t.Errorf("deriveOperationID(%q, %q) = %q, want %q", tc.method, tc.path, got, tc.want)
		}
	}
}

func TestCamelCaseOperationID(t *testing.T) {
	// An explicit operationId from OpenAPI is camel-cased: hyphens, dots,
	// slashes, and spaces become word boundaries. Already-camel input is
	// preserved (echoFoo stays echoFoo, not echofoo).
	cases := []struct {
		in, want string
	}{
		{"echo", "echo"},
		{"getItems", "getItems"},
		{"get-items", "getItems"},
		{"get_items", "getItems"},
		{"GET_ITEMS", "getITEMS"},   // first word lower-cased; subsequent words preserved per JSON convention
		{"List items", "listItems"}, // spaces are word boundaries
		{"", ""},
	}
	for _, tc := range cases {
		got := camelCaseOperationID(tc.in)
		if got != tc.want {
			t.Errorf("camelCaseOperationID(%q) = %q, want %q", tc.in, got, tc.want)
		}
	}
}

// --- integration tests: routes.ts emission ---

func TestGenTSClientEmitsRoutesFile(t *testing.T) {
	requireProtocGenES(t)
	bundleDir, version := seedSingleLayerBundle(t)
	outDir := filepath.Join(t.TempDir(), "client")
	res, err := GenTSClient(bundleDir, outDir, "")
	if err != nil {
		t.Fatalf("GenTSClient: %v", err)
	}
	if res.RoutesFile == "" {
		t.Fatal("GenTSClient: RoutesFile is empty; expected a path to routes.ts")
	}
	if res.RoutesFile != "routes.ts" {
		t.Errorf("RoutesFile = %q, want %q", res.RoutesFile, "routes.ts")
	}
	body, err := os.ReadFile(filepath.Join(outDir, res.RoutesFile))
	if err != nil {
		t.Fatalf("read routes.ts: %v", err)
	}
	got := string(body)

	// Generator header marks the file as derived output (consumers should not
	// hand-edit) and names the bundle layer for traceability.
	for _, want := range []string{
		"@generated by wavefront-bundle gen-ts-client",
		`Source: bundle layer "` + version + `"`,
		// The single route in the fixture is POST /v3/echo with no
		// operationId, so the derived key is `postV3Echo`.
		`postV3Echo`,
		// HTTP method and path appear as literals.
		`method: "POST"`,
		`path: "/v3/echo"`,
		// contract_version is plumbed through verbatim from versions.yaml.
		`contractVersion: "` + version + `"`,
		// Schema constants are referenced — protoc-gen-es names them
		// "<MessageName>Schema" and our fixture's message is "Req".
		`requestSchema: ReqSchema`,
		`responseSchema: ReqSchema`,
		// Import is from the message _pb file; the `import_extension=none`
		// setting means no .js suffix on the specifier.
		`from "./wavefront/gen/`,
	} {
		if !strings.Contains(got, want) {
			t.Errorf("routes.ts missing expected substring %q:\n%s", want, got)
		}
	}
	// Import specifier must not carry a `.js` (`import_extension=none` is the
	// agreed contract).
	if strings.Contains(got, `_pb.js"`) || strings.Contains(got, `_pb.ts"`) {
		t.Errorf("routes.ts must not include file-extension suffix on the message import:\n%s", got)
	}
}

func TestGenTSClientRoutesFileDeterministic(t *testing.T) {
	requireProtocGenES(t)
	bundleDir, _ := seedSingleLayerBundle(t)

	outA := filepath.Join(t.TempDir(), "a")
	if _, err := GenTSClient(bundleDir, outA, ""); err != nil {
		t.Fatalf("GenTSClient first run: %v", err)
	}
	outB := filepath.Join(t.TempDir(), "b")
	if _, err := GenTSClient(bundleDir, outB, ""); err != nil {
		t.Fatalf("GenTSClient second run: %v", err)
	}

	bytesA, err := os.ReadFile(filepath.Join(outA, "routes.ts"))
	if err != nil {
		t.Fatalf("read routes.ts A: %v", err)
	}
	bytesB, err := os.ReadFile(filepath.Join(outB, "routes.ts"))
	if err != nil {
		t.Fatalf("read routes.ts B: %v", err)
	}
	if string(bytesA) != string(bytesB) {
		t.Errorf("routes.ts is not byte-reproducible:\n--- A ---\n%s\n--- B ---\n%s", bytesA, bytesB)
	}
}

// seedMultiContractLayer builds a fixture layer with TWO contracts in a
// single versions.yaml — the v0.2 multi-route shape that's coming in Chunk
// 5.0 but is hand-stitched here so this chunk can exercise the contract
// without waiting for the v0.2 generator. Both contracts share the same
// descriptors.binpb (an FDS with two message types: Ping, Pong); routes.ts
// must emit one entry per contract, sorted by (path, method).
func seedMultiContractLayer(t *testing.T) (bundleDir, version string) {
	t.Helper()
	// Reuse the v0.1 single-route seed to produce a valid layer (descriptors,
	// openapi.json, versions.yaml). Then overwrite versions.yaml with a
	// hand-stitched multi-contract document. The descriptors.binpb already
	// contains the Req message, which is enough for both contracts here.
	bundleDir, version = seedSingleLayerBundle(t)
	pkg := "wavefront.gen.v" + sanitize(version)
	versionsYAML := `version: 1
contracts:
  - contract_version: "` + version + `"
    route: /v3/items
    method: GET
    request_message: ` + pkg + `.Req
    response_message: ` + pkg + `.Req
  - contract_version: "` + version + `-b"
    route: /v3/echo
    method: POST
    request_message: ` + pkg + `.Req
    response_message: ` + pkg + `.Req
`
	path := filepath.Join(bundleDir, version, "versions.yaml")
	if err := os.WriteFile(path, []byte(versionsYAML), 0o600); err != nil {
		t.Fatalf("overwrite versions.yaml: %v", err)
	}
	return bundleDir, version
}

func TestGenTSClientEmitsMultiContractRoutes(t *testing.T) {
	requireProtocGenES(t)
	bundleDir, version := seedMultiContractLayer(t)
	outDir := filepath.Join(t.TempDir(), "client")
	if _, err := GenTSClient(bundleDir, outDir, version); err != nil {
		t.Fatalf("GenTSClient: %v", err)
	}
	body, err := os.ReadFile(filepath.Join(outDir, "routes.ts"))
	if err != nil {
		t.Fatalf("read routes.ts: %v", err)
	}
	got := string(body)

	// Both routes must appear, keyed by their derived operation IDs.
	for _, want := range []string{
		`postV3Echo`,
		`getV3Items`,
		`path: "/v3/echo"`,
		`path: "/v3/items"`,
		`method: "POST"`,
		`method: "GET"`,
	} {
		if !strings.Contains(got, want) {
			t.Errorf("multi-contract routes.ts missing %q:\n%s", want, got)
		}
	}

	// Determinism check: routes must be sorted by (path, method) so two runs
	// produce byte-identical output. The fixture's two routes are /v3/echo
	// then /v3/items in lex order; `postV3Echo` should appear before
	// `getV3Items` in the emitted file.
	echoIdx := strings.Index(got, "postV3Echo")
	itemsIdx := strings.Index(got, "getV3Items")
	if echoIdx < 0 || itemsIdx < 0 {
		t.Fatalf("expected both route keys present in emitted file:\n%s", got)
	}
	if echoIdx > itemsIdx {
		t.Errorf("routes.ts entries are not sorted by (path, method): /v3/echo should appear before /v3/items:\n%s", got)
	}
}

func TestGenTSClientUsesExplicitOperationID(t *testing.T) {
	requireProtocGenES(t)

	// Seed a bundle whose OpenAPI doc carries an explicit operationId for the
	// single operation. The derived key in routes.ts must match the
	// operationId (camel-cased), not the (method, path) fallback.
	const docWithOpID = `{"openapi":"3.0.0","info":{"title":"t","version":"2026-05-17"},
"paths":{"/v3/echo":{"post":{
"operationId":"echoMessage",
"requestBody":{"content":{"application/json":{"schema":{"$ref":"#/components/schemas/Req"}}}},
"responses":{"200":{"content":{"application/json":{"schema":{"$ref":"#/components/schemas/Req"}}}}}}}},
"components":{"schemas":{"Req":{"type":"object","properties":{"text":{"type":"string"}}}}}}`
	bundleDir := t.TempDir()
	src := filepath.Join(t.TempDir(), "openapi.json")
	if err := os.WriteFile(src, []byte(docWithOpID), 0o600); err != nil {
		t.Fatalf("write openapi: %v", err)
	}
	if err := Add(src, bundleDir); err != nil {
		t.Fatalf("Add: %v", err)
	}
	outDir := filepath.Join(t.TempDir(), "client")
	if _, err := GenTSClient(bundleDir, outDir, ""); err != nil {
		t.Fatalf("GenTSClient: %v", err)
	}
	body, err := os.ReadFile(filepath.Join(outDir, "routes.ts"))
	if err != nil {
		t.Fatalf("read routes.ts: %v", err)
	}
	got := string(body)
	if !strings.Contains(got, "echoMessage") {
		t.Errorf("routes.ts should use explicit operationId %q as the map key:\n%s", "echoMessage", got)
	}
	if strings.Contains(got, "postV3Echo") {
		t.Errorf("routes.ts should NOT fall back to derived key when operationId is present:\n%s", got)
	}
}
